---
output: github_document
title: "BACKLOG"
---

<!-- BACKLOG.md is generated from BACKLOG.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/BACKLOG-",
  out.width = "100%"
)
```

## OPEN

- TODO-20200429T1418: Think about ways of linking BACKLOG.Rmd/.md to GitHub
issues and/or vice verso
- TODO-20200502T1642: This should be FALSE in case NEWS.md already exists
- TODO-20200503T0115: Align testing {lifecycle} behavior when README.Rmd exists
- TODO-20200508T0739: Can't get the clipboard to work in a consistent manner
(interactive vs. non-interactive use differs)
- TODO-20200508T0941: Abstracting the last if ... else away would be nice, but I
can't get `return()` and `Recall()` to work when they're not called in the
"correct" frame
- TODO-20200511T1804: Check if badge for license file can be added to README
- TODO-20200728-1134: Pin down reason why deferring doesn't work as desired

## IN PROGRESS

- TODO-YYYYMMDD-3-STARTED-YYYMMDDTHHMM: Some TODO with an date or date time 
like ID to denote when you started working on it

## PARKED

- TODO-YYYYMMDD-2-PARKED-YYYYMMDD: Some TODO that was parked on YYYYMMDD

## CLOSED

- TODO-YYYYMMDD-1-CLOSED-{close_id}: Some TODO that was closed with {close_id} 
which could either be
    - a date or date time like format such as `YYYYMMDD` 
	(e.g. `20200401` and thus `TODO-20200401-1-CLOSED-20200401T1226`) or
	YYYYMMDDTHHMM (e.g. `20200401T1226` and thus 
	`TODO-20200401-1-CLOSED-20200401T1226`)
    - a package version (e.g. `v0.0.1` and 
	`TODO-20200401-1-CLOSED-v0.0.1`)
    - a GitHub issue ID (e.g. `#14` and thus `TODO-20200401-1-CLOSED-#14`)
- TODO-20200506T1417-CLOSED-20200508T1106: selecting from multiple nominal
options cannot be handled via `usethis::ui_yeah()`, so find of realizing that
- TODO-20200511T1807-CLOSED-20200511T1824: Encapsulate `usethis::use_readme_md()` by combining it with `ensure_readme_rmd()`. Closed by `ensure_readme()`
- TODO-20200511T1617-CLOSED-20200511T2207: This is still somewhat "hard-coded"
to `{covr}` and/or `usethis::use_coverage()`. Find more generalistic approaches.
Closed by `ensure_unit_testing_test_coverage()`
