# Ensure package ----------------------------------------------------------

#' @import usethis
#' @importFrom renv install
ensure_package <- function(package) {
  if (!usethis:::is_installed(package)) {
    renv::install(package)
  }
  usethis:::is_installed(package)
}

# Ensure removed files ----------------------------------------------------

#' @importFrom fs file_exists file_delete
#' @importFrom usethis ui_done ui_oops
ensure_removed_file <- function(path) {
  path_0 <- path

  path <- path %>%
    handle_path()

  if (fs::file_exists(path)) {
    fs::file_delete(path)
    if (!fs::file_exists(path)) {
      usethis::ui_done("Succesfully removed {path_0}")
      TRUE
    } else {
      usethis::ui_oops("Unable to remove {path_0}")
      FALSE
    }
  } else {
    usethis::ui_done("{path_0} was already removed")
    TRUE
  }
}

#' @importFrom fs file_exists file_create
#' @importFrom usethis ui_done ui_oops
ensure_existing_file <- function(path, content = NULL) {
  path_0 <- path
  path <- path_0 %>%
    handle_path()
  if (!fs::file_exists(path)) {
    fs::file_create(path)

    # Write content if any was provided:
    if (!is.null(content)) {
      write(content, file = path)
    }

    if (fs::file_exists(path)) {
      usethis::ui_done("Succesfully created {path_0}")
      TRUE
    } else {
      usethis::ui_oops("Unable to create {path_0}")
      FALSE
    }
  } else {
    usethis::ui_done("{path_0} was already created")
    TRUE
  }
}

# Ensure example files are removed ----------------------------------------

ensure_removed_hello_r <- function() {
  "R/hello.R" %>%
    ensure_removed_file()
}

ensure_removed_hello_rd <- function() {
  "man/hello.Rd" %>%
    ensure_removed_file()
}

# DESCRIPTION -------------------------------------------------------------

#' @importFrom git2r config
#' @importFrom usethis use_gpl3_license
ensure_gpl3_license <- function(
  # install_deps_if_missing = TRUE,
  # add_to_description_suggests = TRUE
) {
  result <- try({
    usethis::use_gpl3_license(name = git2r::config()$global$user.name)
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of GPL3 license failed"
  )
}

# Ensure default NAMESPACE is removed -------------------------------------

#' @importFrom fs file_exists
#' @importFrom usethis ui_done
ensure_removed_default_namespace <- function() {
  path_0 <- "NAMESPACE"
  path <- path_0 %>%
    handle_path()

  namespace <- if (fs::file_exists(path)) {
    path %>%
      readLines()
  } else {
    ""
  }
  if (
    all(namespace %in% c("exportPattern(\"^[[:alpha:]]+\")", "")) ||
      !any(namespace %in% "# Generated by roxygen2: do not edit by hand")
    ) {
    path_0 %>%
      ensure_removed_file()
  } else {
    usethis::ui_done("NAMESPACE generated by {{roxygen2}}")
    FALSE
  }
}

# Ensure {renv} -----------------------------------------------------------

#' @import usethis
#' @importFrom here here
#' @importFrom renv activate
#' @importFrom withr with_envvar
ensure_renv_active <- function(upgrade = TRUE) {
  usethis:::check_installed("renv")

  # renv::activate()

  path <- if (get_package_name() != get_package_name(here::here())) {
    handle_path()
  } else {
    NULL
  }

  # c(
  #   get_package_name(),
  #   get_package_name(here::here())
  # ) %>%
  # # path %>%
  #   write(file = "/home/data/renv_path.txt")

  withr::with_envvar(
    new = c("RENV_PROJECT" = NA),
    renv::activate(project = path)
  )
  usethis::ui_done("Package {{renv}} activated")

  TRUE
}

#' @import usethis
#' @importFrom here here
#' @importFrom renv upgrade
#' @importFrom withr with_envvar
ensure_renv_upgraded <- function() {
  usethis:::check_installed("renv")

  # renv::upgrade()

  path <- if (get_package_name() != get_package_name(here::here())) {
    handle_path()
  } else {
    NULL
  }
  renv::upgrade(project = path)
  usethis::ui_done("Package {{renv}} upgraded")

  TRUE
}

# Ensure README -----------------------------------------------------------

#' @importFrom fs file_exists
#' @importFrom renv install
#' @importFrom usethis use_readme_rmd use_package ui_done
ensure_readme_rmd <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  deps <- c(
    "rmarkdown",
    "whisker"
  )
  deps %>%
    handle_deps(install_if_missing = install_deps_if_missing)

  path_0 <- "README.Rmd"
  path <- path_0 %>%
    handle_path()

  if (!fs::file_exists(path)) {
    result <- try(usethis::use_readme_rmd(), silent = TRUE)
    if (inherits(result, "try-error")) {
      if (install_deps_if_missing) {
        usethis:::check_installed("renv")
        renv::install("rmarkdown")
        out <- usethis::use_readme_rmd()
        if (add_to_description_suggests) {
          usethis::use_package("rmarkdown", type = "Suggests")
        }
        out
      } else {
        message(result)
        FALSE
      }
    } else {
      TRUE
    }
  } else {
    usethis::ui_done("{path_0} already exists")
    TRUE
  }

  modify_readme()
}

ensure_knit_readme <- function() {
  suppressMessages(knit_readme())
  TRUE
}

# Ensure generic ----------------------------------------------------------

#' @import usethis
#' @importFrom here here
#' @importFrom fs file_exists
#' @importFrom git2r commit
#' @importFrom renv install
ensure_generic <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE,
  fn,
  fn_dep = NULL,
  deps = character(),
  deps_type = "Suggests",
  path = character(),
  requires_restart = FALSE
) {
  if (length(path)) {
    path_0 <- path
    path <- path %>%
      handle_path()
  }

  if (!length(path) || !fs::file_exists(path)) {
    result <- try(fn(), silent = TRUE)
    if (inherits(result, "try-error")) {
      if (length(deps) && install_deps_if_missing) {
        usethis:::check_installed("renv")
        project <- if (get_package_name() != get_package_name(here::here())) {
          handle_path()
        } else {
          NULL
        }
        renv::install(deps, project = project)
        if (requires_restart) {
          return("restart")
        }
        if (add_to_description_suggests) {
          usethis::use_package(deps, type = dep_type)
        }
        out <- fn()
        out
        # ensure_generic(
        #   install_deps_if_missing = install_deps_if_missing,
        #   add_to_description_suggests = add_to_description_suggests,
        #   fn = fn,
        #   fn_dep = fn_dep,
        #   deps = deps,
        #   deps_type = deps_type,
        #   path = path,
        #   requires_restart = requires_restart
        # )
      } else if (length(fn_dep)) {
        result <- try(fn_dep(), silent = TRUE)
        if (inherits(result, "try-error")) {
          git2r::commit()
        } else {
          stop("Not implemented yet")
        }
      } else {
        message(result)
        FALSE
      }
    } else {
      TRUE
    }
  } else {
    usethis::ui_done("{path_0} already exists")
    TRUE
  }
}

# Ensure NEWS -------------------------------------------------------------

#' @importFrom fs file_exists
#' @importFrom usethis use_news_md
ensure_news_md <- function() {
  path_0 <- "NEWS.md"
  path <- path_0 %>%
    handle_path()

  usethis::use_news_md()
  if (fs::file_exists(path)) {
    TRUE
  } else {
    FALSE
  }
}

# Ensure markdown in roxygen code -----------------------------------------

#' @importFrom usethis use_roxygen_md
ensure_roxygen_md <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  ensure_generic(
    install_deps_if_missing = install_deps_if_missing,
    add_to_description_suggests = add_to_description_suggests,
    fn = usethis::use_roxygen_md,
    deps = "roxygen2"
  )
}

#' #' @importFrom roxygen2md roxygen2md
#' ensure_roxygen2md <- function(
#'   install_deps_if_missing = TRUE,
#'   add_to_description_suggests = TRUE
#' ) {
#'   ensure_generic(
#'     install_deps_if_missing = install_deps_if_missing,
#'     add_to_description_suggests = add_to_description_suggests,
#'     fn = roxygen2md::roxygen2md,
#'     deps = "roxygen2md"
#'   )
#' }

# Ensure NAMESPACE by roxygen2 --------------------------------------------

#' @importFrom roxygen2 roxygenize
ensure_roxygen_namespace <- function(
  install_deps_if_missing = TRUE
) {
  result <- try({
    # usethis:::check_installed("roxygen2")
    deps <- c("roxygen2", "commonmark")
    capture.output(
      deps %>%
        handle_deps(install_if_missing = install_deps_if_missing)
    )
    roxygen2::roxygenize()
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of roxygen NAMESPACE failed",
    .strict = TRUE
  )
}

# Ensure {lifecycle} ------------------------------------------------------

#' @importFrom clipr clipr_available read_clip clear_clip
#' @importFrom fs path
#' @importFrom stringr str_glue
#' @importFrom usethis use_lifecycle use_lifecycle_badge
ensure_lifecycle <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  deps <- c(
    "clipr"
  )
  deps %>%
    handle_deps(install_if_missing = install_deps_if_missing)

  package_name <- get_package_name()

  path_0 <- fs::path("R", stringr::str_glue("{package_name}-package.R"))
  path <- path_0 %>%
    handle_path()
  path %>%
    ensure_existing_file()

  result <- ensure_generic(
    install_deps_if_missing = install_deps_if_missing,
    add_to_description_suggests = add_to_description_suggests,
    fn = usethis::use_lifecycle,
    deps = "r-lib/usethis",
    requires_restart = TRUE
  )

  if (result == "restart") {
    # stop("Restart case not implemented yet")
  }
  # TODO: align with scenario that requires a restart (e.g. if wrong {usethis}
  # version is installed)

  if (clipr::clipr_available()) {
    content <- suppressWarnings(clipr::read_clip())
    content %>%
      write(file = path)
    clipr::clear_clip()
  } else {
    content <- c(
      "## usethis namespace: start",
      "#' @importFrom lifecycle deprecate_soft",
      "## usethis namespace: end",
      "NULL"
    )
    content %>%
      write(file = path)
  }
  # TODO: Temporary fix only! Resolve clipboard issue and remove this code smell

  usethis::use_lifecycle_badge("experimental")

  TRUE
}

# Ensure GitHub remote ----------------------------------------------------

#' @importFrom usethis use_git
ensure_github <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE,
  .strict = FALSE
) {
  # Ensure dependency:
  deps <- "gert"
  capture.output(
    deps %>%
      handle_deps(install_if_missing = install_deps_if_missing)
  )

  # Initialize:
  usethis::use_git()

  # Ensure git remote:
  out <- ensure_git_remote(.strict = .strict)

  if (FALSE) {
    # Ensure git add all:
    ensure_git_add_all(.strict = .strict)

    # Ensure git fetch:
    ensure_git_fetch(.strict = .strict)

    # Ensure git commit:
    ensure_git_commit(.strict = .strict)

    # Ensure git push:
    ensure_git_push(force = TRUE, .strict = .strict)
  }

  out
}

# Ensure GitHub Actions ---------------------------------------------------

#' @importFrom usethis use_github_action_check_standard
ensure_github_actions <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  result <- try({
    ensure_generic(
      install_deps_if_missing = install_deps_if_missing,
      add_to_description_suggests = add_to_description_seuggests,
      # fn = usethis::use_github_actions
      fn = usethis::use_github_action_check_standard
    )
    # usethis::use_github_action_check_standard()
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of GitHub Actions failed"
  )
}

# Ensure test coverage ----------------------------------------------------

#' @importFrom usethis use_coverage
ensure_coverage <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  result <- try({
    deps <- "covr"
    deps %>%
      handle_deps(install_if_missing = install_deps_if_missing)

    ensure_generic(
      install_deps_if_missing = install_deps_if_missing,
      add_to_description_suggests = add_to_description_seuggests,
      fn = usethis::use_coverage
    )

    # Add GitHub Actions workflow:
    modify_github_actions_workflow_add_codecov()
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of code coverage failed",
    .strict = TRUE
  )
}

# Ensure {pkgedown} -------------------------------------------------------

#' @importFrom usethis use_pkgdown use_github_action
ensure_pkgdown <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  result <- try({
    deps <- "pkgdown"
    deps %>%
      handle_deps(install_if_missing = install_deps_if_missing)

    ensure_generic(
      install_deps_if_missing = install_deps_if_missing,
      add_to_description_suggests = add_to_description_suggests,
      fn = usethis::use_pkgdown
    )

    fn <- purrr::partial(usethis::use_github_action, name = "pkgdown")
    ensure_generic(
      install_deps_if_missing = install_deps_if_missing,
      add_to_description_suggests = add_to_description_suggests,
      fn = fn
    )
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of {{pkgdown}} setup failed",
    .strict = TRUE
  )
}

# Ensure vignette ---------------------------------------------------------

#' @importFrom usethis use_vignette
ensure_vignette <- function(
  install_deps_if_missing = TRUE,
  add_to_description_suggests = TRUE
) {
  result <- try({
    # deps <- "pkgdown"
    #   deps %>%
    #     handle_deps(install_if_missing = install_deps_if_missing)

    use_vignette_partial <- purrr::partial(
      usethis::use_vignette,
      name = get_package_name()
    )

    ensure_generic(
      install_deps_if_missing = install_deps_if_missing,
      add_to_description_suggests = add_to_description_seuggests,
      fn = use_vignette_partial
      # deps = deps
    )
  })

  out <- !inherits(result, "try-error")

  handle_return_value(
    out = out,
    result = result,
    message = "Ensurance of vignette setup failed",
    .strict = TRUE
  )
}

# Ensure GitHub push ------------------------------------------------------

ensure_github_push <- function(.strict = FALSE) {
  ensure_git_add_all(.strict = .strict)
  ensure_git_fetch(.strict = .strict)
  ensure_git_commit(
    # message = stringr::str_glue("GitHub Actions ({Sys.time()}))"),
    .strict = .strict
  )
  ensure_git_push(force = TRUE, .strict = .strict)
}

# Ensure good start -------------------------------------------------------

ensure_good_start <- function() {
  output <- list()

  # Example files are removed:
  output$ensure_removed_hello_r <-
    ensure_removed_hello_r()
  output$ensure_removed_hello_rd <-
    ensure_removed_hello_rd()

  # Default NAMESPACE is removed:
  output$ensure_removed_default_namespace <-
    ensure_removed_default_namespace()

  # Renv actived and up to date:
  output$ensure_renv_active <-
    ensure_renv_active()
  output$ensure_renv_upgraded <-
    ensure_renv_upgraded()

  # README exists:
  output$ensure_readme_rmd <-
    ensure_readme_rmd()

  # NEWS exists:
  output$ensure_news_md <-
    ensure_news_md()

  # Markdown in roxygen code:
  output$ensure_roxygen_md <-
    ensure_roxygen_md()

  # Ensure roxygen2-based NAMESPACE:
  output$ensure_roxygen_namespace <-
    ensure_roxygen_namespace()

  # Ensure {lifecycle}:
  output$ensure_lifecycle <-
    ensure_lifecycle()

  # Use GitHub:
  output$ensure_github <-
    ensure_github()
  output$ensure_github_actions <-
    ensure_github_actions()

  # Test coverage:
  output$ensure_coverage <-
    ensure_coverage()

  # Knit README:
  output$ensure_knit_readme <-
    ensure_knit_readme()

  # Vignettes:
  output$ensure_vignette <-
    ensure_vignette()

  # Ensure {pkgdown}:
  output$ensure_pkgdown <-
    ensure_pkgdown()

  output
}
